- name: playbook - openebs.yml
  hosts: all
  gather_facts: true
  become: true
  vars:
    - notebook_user: "{{ lookup('env','USER') }}"
  tasks:
    - name: ping
      ping:

    - name: Create a directory if it does not exist
      ansible.builtin.file:
         path: /var/openebs/local
         state: directory
         mode: '0755'

