- name: playbook - localhost work
  hosts: localhost
  gather_facts: true
  become: false
  vars:
    - notebook_user: "{{ lookup('env','USER') }}"
    - kubespray_folder: "/home/{{ notebook_user }}/git/kubespray5"
  tasks:
    - name: ping
      ping:

    - name: create folder {{ kubespray_folder }}
      file: 
          path: "{{ kubespray_folder }}"
          owner: "{{ notebook_user }}"
          group: "{{ notebook_user }}"
          mode: '0755'
          state: directory

    - name: git clone kubespray into folder {{ kubespray_folder }}
      ansible.builtin.git: 
        repo: https://github.com/kubernetes-sigs/kubespray.git
        dest: "{{ kubespray_folder }}"
        force: yes


    - name: download Vagrantfile
      get_url:
         url: https://raw.githubusercontent.com/aceqbaceq/kubespray_vagrant/master/Vagrantfile
         dest: "{{ kubespray_folder }}"
         mode: '0660'


    - name: download phase-II.yml
      get_url:
         url: https://raw.githubusercontent.com/aceqbaceq/kubespray_vagrant/master/phase-II.yml
         dest: "{{ kubespray_folder }}"
         mode: '0660'


    - name: create folder {{ kubespray_folder }}/python3/ansible for local ansible installation
      file: 
          path: "{{ kubespray_folder }}/python3/ansible"
          owner: "{{ notebook_user }}"
          group: "{{ notebook_user }}"
          mode: '755'
          state: directory



    - name: install apt python3-venv 
      apt:
         name: [ "python3-venv" ]
         state: present


    - name: install ansible in python3 venv
      pip:
        requirements: "{{ kubespray_folder }}/requirements.txt"
        virtualenv: "{{ kubespray_folder }}/python3/ansible"
        virtualenv_site_packages: yes

    - name: print final message
      debug:
        msg: "Preinstallation is complete. Launch in shell >  source {{ kubespray_folder }}/python3/ansible/bin/activate &&  VAGRANT_VAGRANTFILE={{ kubespray_folder }}/Vagrantfile vagrant up"

